[tool.poetry]
name = "test"
version = "0.0.1"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "~3.9"
django="4.2.16"
numpy="2.0.0"
pandas="1.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"