[tool.poetry]
name = "test"
version = "0.0.1"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "~3.9" # PATCH
numpy="1.26.1" # MAJOR

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"